### ISSUE TITLE
ignored files are no longer being colored correctly in PhpStorm

### ISSUE THREAD

**Issue by vernsix** [hsz/idea-gitignore#177] opened 2015-11-19 17:55 UTC
Files and Directories listed in .hgignore file, are not be colored correctly.  Using .gitignore, this works as expected, but not with Mercurial .hgignore.

**Comment by hsz** [comment] 2015-11-19 18:37
@vernsix Thank you for reporting. Do you have in settings `enable ignoring` checked in `Mercurial` row ?

![image](https://cloud.githubusercontent.com/assets/108333/11280152/d2503646-8ef4-11e5-8bd9-a9ebd3db32c1.png)

**Comment by hsz** [comment] 2015-12-23 10:34
Duplicate of #174

**Closed by hsz** 2015-12-23 10:34 UTC
