### ISSUE TITLE
incompatible with idea 2.2

### ISSUE THREAD

**Issue by MeiXXD** [hsz/idea-gitignore#441] opened 2017-08-18 11:14 UTC
Plugin Error
Problems found loading plugins:
The following plugins are incompatible with the current IDE build: .ignore

>.ignore 2.0.4

>IntelliJ IDEA 2017.2.2
Build #IU-172.3757.52, built on August 15, 2017
JRE: 1.8.0_152-release-915-b10 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by hsz** [comment] 2017-08-18 11:17
Duplicate of #408

**Closed by hsz** 2017-08-18 11:17 UTC
