### ISSUE TITLE
I can't find it in IDEA's plugins

### ISSUE THREAD

**Issue by eden214** [hsz/idea-gitignore#449] opened 2017-08-21 15:03 UTC
windows10    idea2017.2.2

**Comment by hsz** [comment] 2017-08-21 15:22
Duplicate of #408

**Comment by eden214** [comment] 2017-08-21 15:29
@hsz I mean I can't FIND .gitignore follow these steps:Preferences > Plugins > Browse repositories... > Search for ".ignore". Not mean I can't USE it. I can find it some idea version before, but it disappeared on 2017.2.2.

**Comment by hsz** [comment] 2017-08-21 15:35
@eden214 because of https://github.com/hsz/idea-gitignore/issues/408#issuecomment-321644030 blacklisted version of the plugin don't appear in the listing.

Future v2.1.0 release (which is in progress now) will be visible again.

**Closed** 2017-08-22 20:16 UTC
Labels: bug, duplicate
