### ISSUE TITLE
gitignore files from gems are shown in the outer ignore rules

### ISSUE THREAD

**Issue by bughit** [hsz/idea-gitignore#410] opened 2017-08-07 16:00 UTC
RM 2017.1.5 idea-gitignore 2.0.4

e.g. ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/Documentation/.gitignore

**Comment by CAD97** [comment] 2017-08-20 03:22
At the very least related to #401

**Comment by hsz** [comment] 2017-08-22 20:06
Duplicate of #401

**Closed** 2017-08-22 20:07 UTC
Labels: bug, duplicate, ready for release
