### ISSUE TITLE
Accessing 'IgnoreFilesIndex' during processing 'FrameworkDetectionIndex'.

### ISSUE THREAD

**Issue by NIA** [hsz/idea-gitignore#472] opened 2017-09-06 08:06 UTC
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [X] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

_Reopening big project just after IDEA startup caused this error_

```
Accessing 'IgnoreFilesIndex' during processing 'FrameworkDetectionIndex'. Nested different indices processing may cause deadlock
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.intellij.util.indexing.IndexAccessValidator.checkAccessingIndexDuringOtherIndexProcessing(IndexAccessValidator.java:37)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1002)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1081)
	at com.intellij.util.indexing.FileBasedIndexImpl.getValues(FileBasedIndexImpl.java:945)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.getEntries(IgnoreFilesIndex.java:233)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.getFiles(IgnoreFilesIndex.java:249)
	at mobi.hsz.idea.gitignore.lang.kind.GitLanguage.getOuterFiles(GitLanguage.java:107)
	at mobi.hsz.idea.gitignore.indexing.ExternalIndexableSetContributor.getAdditionalFiles(ExternalIndexableSetContributor.java:77)
	at mobi.hsz.idea.gitignore.indexing.ExternalIndexableSetContributor.getAdditionalProjectRootsToIndex(ExternalIndexableSetContributor.java:102)
	at com.intellij.util.indexing.IndexableSetContributor.getProjectRootsToIndex(IndexableSetContributor.java:39)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:2494)
	at com.intellij.util.indexing.FileBasedIndexImpl.iterateIndexableFiles(FileBasedIndexImpl.java:2444)
	at com.intellij.util.indexing.FileBasedIndexImpl.projectIndexableFiles(FileBasedIndexImpl.java:1188)
	at com.intellij.util.indexing.FileBasedIndexImpl$15.convert(FileBasedIndexImpl.java:1058)
	at com.intellij.util.indexing.FileBasedIndexImpl$15.convert(FileBasedIndexImpl.java:1035)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1007)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1081)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:961)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager.a(FrameworkDetectionManager.java:211)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager.a(FrameworkDetectionManager.java:178)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager.access$000(FrameworkDetectionManager.java:59)
	at com.intellij.framework.detection.impl.FrameworkDetectionManager$1.run(FrameworkDetectionManager.java:66)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:267)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2405)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:279)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:398)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Steps to Reproduce

1. _Started IDEA with some project_
2. _Soon reopened another (quite big) project_
3. _IDEA started indexing it, and Immediately the error appeared in event log._

**Expected behavior:** _No error_

**Actual behavior:** _An exception_

**Reproduces how often:** _Very rare, happened only once_

### Versions

**Plugin:** 

```
2.2.0
```

**IDE:** 

```
IntelliJ IDEA 2016.1.4
Build #IU-145.2070, built on August 2, 2016
JRE: 1.8.0_112-release-b408 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**OS:** 

```
Windows 10 64-bit
```

**Comment by hsz** [comment] 2017-09-12 07:03
@NIA Thanks for the report! I'll mark it as a duplicate of #473 - please follow this thread.

**Closed by hsz** 2017-09-12 07:03 UTC
Labels: bug, duplicate
