### ISSUE TITLE
Rider (Released version 2017.1.1) causes nullpointerexception with plugin

### ISSUE THREAD

**Issue by appsolutegeek** [hsz/idea-gitignore#451] opened 2017-08-23 08:30 UTC
Hi,

The plugin throws a Isolated exception, the following is in the details.

```
Isolated exception
kotlin.KotlinNullPointerException
	at com.jetbrains.rider.daemon.components.RiderMarkupHost$1.invoke(RiderMarkupHost.kt:46)
	at com.jetbrains.rider.daemon.components.RiderMarkupHost$1.invoke(RiderMarkupHost.kt:26)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$2.invoke(Interfaces.kt:163)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$2.invoke(Interfaces.kt:122)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$1.invoke(Interfaces.kt:142)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$1.invoke(Interfaces.kt:122)
	at com.jetbrains.rider.util.reactive.IViewableMap$adviseAddRemove$1.invoke(Interfaces.kt:154)
	at com.jetbrains.rider.util.reactive.IViewableMap$adviseAddRemove$1.invoke(Interfaces.kt:122)
	at com.jetbrains.rider.util.reactive.Signal.fire(Signal.kt:27)
	at com.jetbrains.rider.util.reactive.ViewableMap.put(ViewableMap.kt:33)
	at com.jetbrains.rider.document.DocumentHost.viewEditableEntity$rider(DocumentHost.kt:97)
	at com.jetbrains.rider.document.DocumentHost$1$1.run(DocumentHost.kt:68)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:926)
	at com.jetbrains.rider.document.DocumentHost$1.invoke(DocumentHost.kt:63)
	at com.jetbrains.rider.document.DocumentHost$1.invoke(DocumentHost.kt:40)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$2.invoke(Interfaces.kt:163)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$2.invoke(Interfaces.kt:122)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$1.invoke(Interfaces.kt:142)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$1.invoke(Interfaces.kt:122)
	at com.jetbrains.rider.util.reactive.IViewableMap$adviseAddRemove$1.invoke(Interfaces.kt:154)
	at com.jetbrains.rider.util.reactive.IViewableMap$adviseAddRemove$1.invoke(Interfaces.kt:122)
	at com.jetbrains.rider.util.reactive.Signal.fire(Signal.kt:27)
	at com.jetbrains.rider.util.reactive.ViewableMap.put(ViewableMap.kt:33)
	at com.jetbrains.rider.framework.impl.RdMap$put$1.invoke(RdMap.kt:164)
	at com.jetbrains.rider.framework.base.RdReactiveBase.localChange(RdReactiveBase.kt:45)
	at com.jetbrains.rider.framework.impl.RdMap.put(RdMap.kt:164)
	at com.jetbrains.rider.document.DocumentHost.registerModelDocument$rider(DocumentHost.kt:295)
	at com.jetbrains.rider.editors.TextControlHost.bindEditor$rider(TextControlHost.kt:268)
	at com.jetbrains.rider.editors.TextControlHost.editorCreated(TextControlHost.kt:213)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy37.editorCreated(Unknown Source)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:223)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:195)
	at mobi.hsz.idea.gitignore.util.Utils.createPreviewEditor(Utils.java:369)
	at mobi.hsz.idea.gitignore.outer.OuterIgnoreWrapper.<init>(OuterIgnoreWrapper.java:119)
	at mobi.hsz.idea.gitignore.outer.OuterIgnoreLoaderComponent$IgnoreEditorManagerListener.fileOpened(OuterIgnoreLoaderComponent.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:437)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:380)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:373)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:44)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:230)
	at com.sun.proxy.$Proxy112.fileOpened(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$null$7(FileEditorManagerImpl.java:938)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$5$1.run(FileEditorManagerImpl.java:1031)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.flushRequest(FocusManagerImpl.java:655)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.flushNow(FocusManagerImpl.java:639)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.flushIdleRequests(FocusManagerImpl.java:609)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:61)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:107)
	at com.intellij.openapi.util.EdtRunnable.lambda$run$0(EdtRunnable.java:27)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2632)
	at com.intellij.openapi.util.EdtRunnable.run(EdtRunnable.java:25)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by hsz** [comment] 2017-08-23 09:39
Duplicate of #385

**Closed by hsz** 2017-08-23 09:39 UTC
