### ISSUE TITLE
project folders are reported as ignored files that are tracked

### ISSUE THREAD

**Issue by bughit** [hsz/idea-gitignore#411] opened 2017-08-07 16:03 UTC
RM 2017.1.5 idea-gitignore 2.0.4
This is new in 2.0.4.  On project open it alerts about ignored tracked files and the details dialog shows just the project folder name.

**Comment by attaboy** [comment] 2017-08-08 18:35
I have this issue as well. The project folder doesn't expand to show any files, and the list of commands below is blank:

<img width="524" alt="ignore" src="https://user-images.githubusercontent.com/71433/29088335-bd665846-7c46-11e7-9a83-3d1bcc0cfd88.png">

**Comment by tobske** [comment] 2017-08-10 06:59
Same here with Intellij IDEA 2017.2.1 and .ignore 2.0.4

**Comment by tobske** [comment] 2017-08-10 07:01
I did the following to keep this message from showing up:
Open .gitignore file and select "Add unversioned files" that is shown to me at the top. After that I deleted the newly added lines in the .gitignore so the does not have any changes. The next time I opened the project the message did not show op. Can maybe someone try this and confirm that it is a work around?

**Comment by benjyblack** [comment] 2017-08-10 14:08
Do you guys have a `.dockerignore` file in your project? I'm wondering if the plugin is confusing that with a `.gitignore` file.

**Comment by jochenhebbrecht** [comment] 2017-08-10 14:30
I'm facing the same problem (IDEA 2017.2.1 and .ignore 2.0.4). I don't have a `.dockerignore` file

**Comment by pbienick** [comment] 2017-08-14 11:58
Same problem here, but I tried what tobske suggested above and it seems to have worked!

**Comment by mbuzdalov** [comment] 2017-08-14 19:38
I confirm this problem. IDEA 2017.2.1, .ignore 2.0.4, I have only a .gitignore file.

**Comment by aungthumoe5** [comment] 2017-08-18 02:18
Possible duplicate issue
https://github.com/hsz/idea-gitignore/issues/400

**Comment by hsz** [comment] 2017-08-20 23:19
Duplicate of #400

**Closed by hsz** 2017-08-20 23:19 UTC
Labels: bug
