### ISSUE TITLE
InvalidVirtualFileAccessException

### ISSUE THREAD

**Issue by mdufresne** [hsz/idea-gitignore#107] opened 2015-04-13 17:07 UTC
```
Accessing invalid virtual file: file://C:/Users/mark.d/Documents/TestApp/.gitignore; original:390865; found:-
com.intellij.openapi.vfs.InvalidVirtualFileAccessException: Accessing invalid virtual file: file://C:/Users/mark.d/Documents/PollwarePolls/.gitignore; original:390865; found:-
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.c(PersistentFSImpl.java:332)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.contentsToByteArray(PersistentFSImpl.java:488)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:108)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:102)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.loadText(LoadTextUtil.java:414)
	at com.intellij.psi.SingleRootFileViewProvider$VirtualFileContent.getText(SingleRootFileViewProvider.java:494)
	at com.intellij.psi.SingleRootFileViewProvider.getContents(SingleRootFileViewProvider.java:339)
	at com.intellij.psi.impl.source.PsiFileImpl.b(PsiFileImpl.java:184)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:758)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:966)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:779)
	at mobi.hsz.idea.gitignore.util.CacheMap$4.run(CacheMap.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at mobi.hsz.idea.gitignore.util.CacheMap.runVisitorInReadAction(CacheMap.java:145)
	at mobi.hsz.idea.gitignore.util.CacheMap.add(CacheMap.java:83)
	at mobi.hsz.idea.gitignore.IgnoreManager$4$1.run(IgnoreManager.java:320)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Comment by hsz** [comment] 2015-04-18 08:05
@mdufresne Thank you for reporting.

What did you do when you got this issue ? How can I reproduce this bug ?

**Comment by kuc** [comment] 2015-05-11 09:45
This issue should not be listed in changelog as "fixed", if it's closed as "cannot reproduce".

**Comment by hsz** [comment] 2015-05-11 09:47
@kuc Thanks for pointing it out - it was automatically generated with the new tool that I've used.

**Comment by stof** [comment] 2015-07-31 10:11
I got a similar error:

```
Accessing invalid virtual file: file:///home/stof/Code/symfony/symfony/src/Symfony/Component/ExpressionLanguage/.gitignore; original:42028; found:-
com.intellij.openapi.vfs.InvalidVirtualFileAccessException: Accessing invalid virtual file: file:///home/stof/Code/symfony/symfony/src/Symfony/Component/ExpressionLanguage/.gitignore; original:42028; found:-
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.c(PersistentFSImpl.java:332)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.contentsToByteArray(PersistentFSImpl.java:488)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:108)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:102)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.loadText(LoadTextUtil.java:414)
	at com.intellij.psi.SingleRootFileViewProvider$VirtualFileContent.getText(SingleRootFileViewProvider.java:497)
	at com.intellij.psi.SingleRootFileViewProvider.getContents(SingleRootFileViewProvider.java:342)
	at com.intellij.psi.impl.source.PsiFileImpl.b(PsiFileImpl.java:184)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:758)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:966)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:779)
	at mobi.hsz.idea.gitignore.util.CacheMap$4.run(CacheMap.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:872)
	at mobi.hsz.idea.gitignore.util.CacheMap.runVisitorInReadAction(CacheMap.java:145)
	at mobi.hsz.idea.gitignore.util.CacheMap.add(CacheMap.java:83)
	at mobi.hsz.idea.gitignore.IgnoreManager$5$1.run(IgnoreManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Closed** 2015-07-31 10:53 UTC
Labels: bug
