### ISSUE TITLE
"You are editing file which is ignored" warning after upgrading to IDEA 2017.1

### ISSUE THREAD

**Issue by tlaak** [hsz/idea-gitignore#351] opened 2017-03-28 11:51 UTC
I'm getting `.i* You are editing file which is ignored` warnings for random files after I upgraded to IntelliJ IDEA 2017.1. The warning might disappear when restarting IDEA, but it might also reappear for one or more different files.

The files in case are not ignored and they show up in git as expected.

**Comment by beruic** [comment] 2017-03-29 14:04
It also uses a lot of CPU when editing the `.gitignore` file

**Comment by snazy** [comment] 2017-03-29 14:12
NIT: maybe a good chance to correct the spelling to `You are editing a file which is ignored` or rephrase. ;)

**Comment by slegdon** [comment] 2017-03-29 16:10
I get this where I have an entry in .gitignore for /target and part of my source tree has /target/ in it...

**Comment by mattoz0** [comment] 2017-04-03 04:01
+1

Also getting this error. After updating to 2017.1 files are ignored at random. If cache is invalidated or IDE is restarted then all files go back to normal. 

After a few minutes another file (not necessarily the same file) will become ignored. Might need to uninstall plugin till a fix is applied as this stops your ability to add or commit a file to your repo.

**Comment by mistercam** [comment] 2017-04-04 12:28
I'm having the same issue with 2017.1 . I've temporarily disabled the plugin.

**Comment by eburi** [comment] 2017-04-05 11:32
I just installed the plugin and I like, except for this issue. I get seemingly random messages that I'm editing an ignored file, when the file I'm editing is not ignored by any .i*-File.

Uninstalling...

**Comment by mtnbikenc** [comment] 2017-04-11 12:38
I have also encountered this issue.  In my case, I have a global ignore file at ~/.config/git/ignore which contains on `.idea/`.  In the project where I am seeing random ignored files, I also have a .gitignore which contains `.idea/`.  If I remove the global gitignore file, things appear to go back to normal.  Disabling the plugin for now.

**Comment by sergiusz-roszczyk** [comment] 2017-04-17 11:08
I can confirm that this also happens on my projects based on git. One is local git repository without remote origins, another one is with corporate gitolite server. In both cases files marked as ignored are totally random.

Most recent scenario:
1) Open project in Idea
2) Move 4 java files into sub-package
3) One of the files in parent package was marked as "ignored"
4) Restart Idea
5) File is not marked as ignored

This behavior prevents using commit from Idea but everything is commit fine when doing from command line or other GUI tool.

I tried putting this line in .gitignore. It changed state for the current session but didn't prevent from happen after Idea restart.
`!/src/main/`

IntelliJ IDEA 2017.1.1
Build #IU-171.4073.35, built on April 6, 2017
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4

**Comment by qmg-gkalogiros** [comment] 2017-04-21 08:26
I started having the same problem after I upgraded to Intellij 2017.1

IntelliJ IDEA 2017.1.1
Build #IU-171.4073.35, built on April 6, 2017
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.1

.ignore
Version: 1.7.6

**Comment by tnc-tianwen** [comment] 2017-05-19 00:55
Same here

PhpStorm 2017.1.4
Build #PS-171.4694.2, built on May 16, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

.ignore
Version: 1.7.6

**Comment by LiranBri** [comment] 2017-05-21 11:47
same here

**Comment by dluc** [comment] 2017-06-02 01:30
+1

**Closed** 2017-07-29 23:13 UTC
Labels: bug, ready for release

**Comment by AveVlad** [comment] 2017-08-09 17:09
same here

**Comment by kevinhaas** [comment] 2017-08-29 22:05
Has this been fixed?

**Comment by AveVlad** [comment] 2017-08-30 11:50
@kevinhaas easy man

![image](https://user-images.githubusercontent.com/2889662/29870912-768731ae-8d92-11e7-87cf-d6b771cdbaf3.png)

**Comment by beruic** [comment] 2017-09-04 07:59
@AveVlad That was not really an answer to @kevinhaas question.

**Comment by ClaudeHangui** [comment] 2017-09-12 19:04
l'm using Android Studio and had the same issue with one of my layouts.....and I can confirm that updating the gitignore plugin solved the issue (for me at least.......)

**Comment by jbreckmckye** [comment] 2017-09-21 09:30
I updated to 2.2.1 and the issue disappeared.

![image](https://user-images.githubusercontent.com/3148617/30689091-df59b978-9eb7-11e7-881f-f2013733cf01.png)

This was with WebStorm 2017.2

**Comment by mamiu** [comment] 2017-10-30 20:59
The same problem in PyCharm for a `.pot` file.

**Comment by roman4e** [comment] 2018-04-14 11:40
PhpStorm 2018.1 the issue is still present. Ignore version 2.5.0 (seems latest)
![screenshot_144](https://user-images.githubusercontent.com/10156713/38767832-b526a7ca-3ff1-11e8-983f-088b99b9f24a.png)

**Comment by PiotrSzlagura** [comment] 2018-09-06 07:44
Same problem on PhpStorm 2018.2
Plugin version: 3.0.0.182

**Comment by D-W-X** [comment] 2018-10-03 11:37
Same problem on idea 2018.2.4 ,
Plugin version: 3.0.0.182
Thank you.

**Comment by Gixx** [comment] 2019-05-20 08:01
Same problem on PHPStorm 2019.1.2
Plugin version: v3.1.1.191
Thank you.

**Comment by leereichardt** [comment] 2019-06-25 04:14
How do we get this issue reopened again as there still seems to be a problem

PHPStorm 2019.1
Plugin version: v3.1.2.191

**Comment by manishkumr** [comment] 2019-06-28 01:40
I am having the same issue recently with PyCharm. I am currently using .ignore v3.1.2.191 and Pycharm version: 

PyCharm 2019.1.1 (Professional Edition)
Build #PY-191.6605.12, built on April 3, 2019
JRE: 11.0.2+9-b159.34 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by northlander** [comment] 2019-09-07 13:05
Same issue with Rider 2019.2
Plugin 3.2.2.192
Mac OS

**Comment by gabriel-TheCode** [comment] 2019-12-03 10:46
Same issue with Android Studio 3.5.2
Build #AI-191.8026.42.35.5977832, built on October 30, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by rishabhdeepsingh** [comment] 2020-09-08 20:27
The issue is still there on CLion 2020.2.1

**Comment by IslamSakrak** [comment] 2020-11-09 12:05
The same issue still going on

**Comment by gabriel-TheCode** [comment] 2020-11-09 13:50
I had solved this by manually adding the affected files in git. 
Go to file, right click, Git -> Add

**Comment by mbXian** [comment] 2021-06-23 06:46
idea 2021 
solved by restart !
