### ISSUE TITLE
Incompatible with IDEA 2017.2.2

### ISSUE THREAD

**Issue by Danamir** [hsz/idea-gitignore#424] opened 2017-08-16 07:46 UTC
Hello, after updating to IDEA 2017.2.2 I have the following error displayed : 
```
Plugin Error
Problems found loading plugins:
The following plugins are incompatible with the current IDE build: .ignore
```

Without any more details. The plugin is then automatically disabled by IDEA.
I tried with the plugin version from the IntelliJ repository (1.7.6) and the latest version from Github (2.0.4) with the same error.

IDEA Build information from Help/About: 
```
IntelliJ IDEA 2017.2.2
Build #IU-172.3757.52, built on August 15, 2017
JRE: 1.8.0_152-release-915-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

[Edit] : sorry, this is the same bug as #408, you can close this one...

**Comment by martinreck** [comment] 2017-08-16 07:51
This problem seems to be platform independent. Same problem on macOS Sierra:
```
IntelliJ IDEA 2017.2.2
Build #IU-172.3757.52, built on August 15, 2017
JRE: 1.8.0_152-release-915-b10 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```

**Comment by hsz** [comment] 2017-08-16 08:27
Thanks for the report. This is a duplicate of #408

**Closed by hsz** 2017-08-16 08:27 UTC
