### ISSUE TITLE
Configure ignored ignore files

### ISSUE THREAD

**Issue by tflori** [hsz/idea-gitignore#352] opened 2017-03-30 04:41 UTC
Lets assume we have a node package with a `.npmignore` that says `.gitignore` should not be contained in the package. I (IMHO) don't want this file to be grayed out in the IDE.

It is of course even more worse when you don't want your test files in the package or even the sources. And the feature "hide ignored files" (what is a reasonable feature for me) can not be used.

Yes, I want to be able to add files to `.npmignore` but the project tree should only show what files are ignored in `.gitignore`.

**Comment by bobbylight** [comment] 2017-04-02 17:43
I'm somewhat of a newbie to publishing npm packages, but I agree that .npmignore files should either not be parsed by this plugin, or have special treatment/configuration somehow.  I have a TypeScript project, with the entire src/ folder specified in .npmignore, as I only want to publish the generated JS.  This plugin is currently marking all of my .ts files as "ignored," which they really shouldn't be.  Being excluded from an npm package is not the same thing as a file being ignored for source control purposes, etc.

**Comment by hsz** [comment] 2017-05-31 22:22
Duplicate of #356

**Closed by hsz** 2017-05-31 22:22 UTC
Labels: duplicate
