### ISSUE TITLE
.ignore 2.0.4 is not working in Intellij IDEA 2017.2.2

### ISSUE THREAD

**Issue by Maksym-dev** [hsz/idea-gitignore#442] opened 2017-08-18 21:20 UTC
In Event Log following message is shown:

Plugin Error
Problems found loading plugins:
The following plugins are incompatible with the current IDE build: .ignore

**Comment by hsz** [comment] 2017-08-18 21:29
Duplicate of #408

**Closed by hsz** 2017-08-18 21:29 UTC
