### ISSUE TITLE
Appears when a file is saved：Unable to save settings: Failed to save settings. Please restart PhpStorm 

### ISSUE THREAD

**Issue by catcoder** [hsz/idea-gitignore#555] opened 2018-07-20 02:15 UTC
PHPStream use .ignore 2.6.2,
When i saving a file, a popup window showing:
![image](https://user-images.githubusercontent.com/834176/42979605-a720feb8-8c05-11e8-8a5d-c5449614b914.png)

**Comment by hsz** [comment] 2018-07-20 07:53
@catcoder Can you please provide more details using the issue template?

**Comment by hsz** [comment] 2018-07-20 10:52
Duplicate of #552

**Closed by hsz** 2018-07-20 10:52 UTC
Labels: information needed
