### ISSUE TITLE
Incompatible with Idea 2017.2.2

### ISSUE THREAD

**Issue by codeseedr** [hsz/idea-gitignore#427] opened 2017-08-16 10:45 UTC
Got this message after Idea upgrade:
```
Plugin Error
		Problems found loading plugins:
		The following plugins are incompatible with the current IDE build: .ignore
```

**Comment by hsz** [comment] 2017-08-16 10:58
Duplicate of #408

**Closed by hsz** 2017-08-16 10:58 UTC
Labels: bug, duplicate
