### ISSUE TITLE
Ignore filed message.

### ISSUE THREAD

**Issue by massoud12345** [hsz/idea-gitignore#370] opened 2017-05-31 15:55 UTC
Hi,
I keep getting the pop up in the bottom right corner.
There used to be commands listed but I manually ran them. They are now not showing up any longer but the Ignored files found message still appears as shown below.
Thank you
![image](https://cloud.githubusercontent.com/assets/11024427/26641275/eb1a27e8-45de-11e7-8e1c-a6636a1a75df.png)

**Comment by julienfalque** [comment] 2017-05-31 19:16
Do you include several projects inside the same window? If so, I think this is a duplicate of #359. Could you try opening the included projects in their own windows instead, and see if you are able to list the ignored files that are tracked?

**Comment by massoud12345** [comment] 2017-05-31 19:18
Thanks Julien.
What do you mean by inside the same window?

**Comment by julienfalque** [comment] 2017-05-31 19:31
I'm talking about the fact that when you are on a project and you open another one (via _File > Open..._), you can _add_ the second project to the project view of the first window, so you get two projects inside a single window. This is how I managed to get the issue I reported, which may be the same here, hence my question.

**Comment by massoud12345** [comment] 2017-05-31 19:33
Thanks but this is not what I am getting the error. I am only opening one
project.

**Comment by richardhooper** [comment] 2017-07-19 11:57
+1 for this.  I have exactly the same issue, the popup appears every time on startup, but the dialog only shows the root dir of my project, with no details.  I haven't got multiple projects open, and in fact I don't even have that option in the Open Project dialog (despite being on PHPS 2017.2).

**Comment by hsz** [comment] 2017-08-20 23:28
Thanks guys for the report!
To keep it clean - I'll mark it as a duplicate of #400.

**Closed by hsz** 2017-08-20 23:28 UTC
