### ISSUE TITLE
Plugin not compatible on latest Intellij EAP

### ISSUE THREAD

**Issue by SUPERCILEX** [hsz/idea-gitignore#408] opened 2017-08-03 17:00 UTC
EAP info:
```
IntelliJ IDEA 2017.2.2 EAP
Build #IU-172.3757.5, built on August 1, 2017
```

Error message:
```
Plugin Error
Problems found loading plugins:
The following plugins are incompatible with the current IDE build: .ignore
```

**Comment by treasure33** [comment] 2017-08-04 04:51
I have the same problem.
`Gogland (1.0 Preview) 1.0 EAP Build #GO-172.3757.2, built on August 1, 2017`
`Version: 2.0.4`

**Comment by MerlinPong** [comment] 2017-08-05 04:55
same issue here, eagerly asking for an update

**Comment by thaJeztah** [comment] 2017-08-05 16:55
Wondering if it's just due to this; https://github.com/hsz/idea-gitignore/blob/9c534e64ceb145b14bc1e0d214d2a7c3ad0ee891/resources/META-INF/plugin.xml#L113

> Starting with 2016.2 the build number may also have multiple components: IU-162.94, IU-162.94.11, IU-162.94.11.256.42. This gives more flexibility for third-party plugins and IDE developers. Plugins may specify compatibility versions more precisely; IDE vendors may have build numbers that are based on a specific IntelliJ Platform version and also specify additional internal version (e.g. 256.42 in XX-162.94.11.256.42) to allow plugin developers for their IDE to specify compatibility.

http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/build_number_ranges.html

**Comment by jwfearn** [comment] 2017-08-07 18:22
Also seeing this issue with this configuration:
IntelliJ IDEA 2017.2.2 EAP
Build #IU-172.3757.5, built on August 1, 2017
JRE: 1.8.0_152-release-915-b10 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by qJkee** [comment] 2017-08-09 13:54
Same problem

**Comment by solcates** [comment] 2017-08-09 22:33
same here, missing .ignore :(

**Comment by thaJeztah** [comment] 2017-08-09 23:39
Just stating the obvious (I personally don't have experience with developing IntelliJ), but if someone here _has_; this plugin is open source - the author most likely maintains it in his spare time. [contributions are welcome](https://github.com/hsz/idea-gitignore/blob/master/CONTRIBUTING.md) so if this plugin is essential for your day-to-day work, and you have some time to spare; open a pull request 👍

**Comment by Kurre** [comment] 2017-08-10 05:42
Updating the version constraint to `since-build="162"` (or removing it altogether) will fix the situation.

On `META-INF/plugin.xml` file
https://github.com/hsz/idea-gitignore/blob/9c534e64ceb145b14bc1e0d214d2a7c3ad0ee891/resources/META-INF/plugin.xml#L113

But I need to monitor that everything is in working order.
Dunno what would be the correct way to handle this..maybe that `<idea-version since-build="162"/> ` would be fine?

**Comment by Adev24** [comment] 2017-08-10 10:05
PhpStorm 2017.2.2 EAP (172.3757.34) same problem
updating/deleting <idea-version ...> not help

**Comment by hsz** [comment] 2017-08-10 19:03
Ok, it appears that `v2.0.4` has been blacklisted in the latest IntelliJ code build:

https://github.com/JetBrains/intellij-community/blob/172.3861/platform/platform-resources/src/brokenPlugins.txt#L33

> mobi.hsz.idea.gitignore 1.2 1.3 1.3.3 1.4.1 1.5 1.6 1.7.5 1.7.6 2.0.4

Looks like it will be automatically fixed with the next bumped version number.

CC: 
@drealecs @dcarbone @filiphr @BorzdeG @Caravus @jwfearn @justinlynn @msadakov @Kendos-Kenlen @liayn @gl3b4ik @Scott-G @potto007 @Kurre @SUPERCILEX @treasure33 @MerlinPong @thaJeztah @jwfearn @qJkee @solcates @F21 @favadi @damagedcode @DexterHD @cbednarski @Scratch-net @msadakov @npiganeau @klauern @zhezh09 @Badbits @michael1011 @damagedcode

**Comment by filiphr** [comment] 2017-08-10 19:13
Thats great. Does someone know why they would do that? 

I know that the issue with the indexing was pretty bad, but it was fixed in 2.x as far as I remember.

**Comment by hsz** [comment] 2017-08-10 19:24
@nicity Can you explain us, what's the policy of blacklisting the plugin versions?

**Comment by nicity** [comment] 2017-08-10 20:37
We get too many user reports about users having performance problems with .gitignore plugin. 
Even latest plugin version has such performance problems.
Our current plan is to disable all available plugin versions until there is one without performance problems. 
Good news is that we can help to make proper implementation. 
E.g. *nothing* should be done during processing virtual file events, IgnoreFileIndex.getKeys() should not be called mobi.hsz.idea.gitignore.IgnoreManager.isFileIgnored(VirtualFile) is called, etc

**Comment by hsz** [comment] 2017-08-11 06:36
@nicity thank you for the response!

Can you share with me the details about all problems that you have noticed (thread dumps, stack traces, good practices)?
In what way can you help me with the proper implementation?

**Comment by nicity** [comment] 2017-08-11 12:35
Let's start with https://github.com/hsz/idea-gitignore/issues/415

**Comment by zman0900** [comment] 2017-08-15 22:43
Just adding that IntelliJ 2017.2.2 was released today and the plugin continues to be blocked:

```
6:32 PM	Plugin Error
				Problems found loading plugins:
				The following plugins are incompatible with the current IDE build: .ignore
```

**Comment by mbirgi** [comment] 2017-08-16 13:50
Just installed Version 2.0.4 manually in Webstorm 2017.2.2 (build #WS-172.3757.55) and got the same error:
16.08.17
15:40	Plugin Error
			Problems found loading plugins:
			The following plugins are incompatible with the current IDE build: .ignore

**Comment by davideas** [comment] 2017-08-18 20:33
@hsz, is it possible to release a patch version only for this issue and so you can continue your development for the minor release more quietly?
This is more than critical, it's blocking.

Thanks and great plugin by the way!

**Comment by hsz** [comment] 2017-08-18 20:37
@davideas I cannot release any new version if I'll not fix #415 - @nicity (JetBrains member) pointed out performance issues that appears for many of their users.

I'm going to work on it tomorrow.

**Comment by CAD97** [comment] 2017-08-20 03:20
You should probably update the title now that 2017.2.2 is released to avoid more duplicates. (`s/latest IntelliJ EAP/IntelliJ 2017.2.2` or similar)

**Comment by justinlynn** [comment] 2017-08-21 02:52
Workaround for users who are *willing to put up with the inefficiencies and slow nature of the plugin*:

1. Ensure that all IDEA instances are closed
2. In the `/lib` subdirectory of the IDEA installation root, open the `resources.jar` file using your favourite compressed files browser (engrampa works well, if you're using MATE GNU/Linux)
3. Inside that jar file, edit the file `/brokenPlugins.txt` placing a comment `//` before the line containing the ignore plugin classname and version listing. It's the only line containing 'ignore' in the file.
4. Once saved, your file explorer should prompt you to update the file within the jar. Choose to do this.
5. Start IDEA. It should load the plugin as expected. If it does not, check to ensure the plugin hasn't been disabled in the plugin settings menu. If it has enable it and restart. The plugin should now work as expected (slowly).

Please note that this does not fix the underlying issues which caused Jetbrains to blacklist this plugin. The workaround simply overrides the blacklist Jetbrains have put in place. 

*DO NOT report speed issues after force enabling this plugin.*

It would be best if Jetbrains would put in place some user interaction informing users of why the plugin has been disabled and present the user with a choice, tainting any reports from them if they choose to ignore the warning. However, we work with what we're given - and in some cases a workaround is needed; so, here it is.

**Comment by robert-cody** [comment] 2017-08-21 03:51
Workaround doesn't work on Mac because app can't start if it's files checksums are incorrect. Any ideas?

**Comment by justinlynn** [comment] 2017-08-21 04:03
@robert-cody My apologies, I don't run on OS X so I'm not able to try out any possible fixes. Perhaps there's some sort of local mode in which you can override checksums? I'm really not familiar with OS X integrity protection.

**Comment by hsz** [comment] 2017-08-21 05:20
During the weekend I have fixed a couple of issues (including the one related to the performance). In a few days I'm going to release new version of the plugin.
Is anyone interested in trying RC?

**Comment by justinlynn** [comment] 2017-08-21 05:21
@hsz :+1: happy to do so

**Comment by robert-cody** [comment] 2017-08-21 06:40
Cross-platform (including macOS) force-enabling plugin:
**ANY NEXT STEP CAN BREAK ANYTHING IN THE WORLD, DO IT ON YOUR OWN RISK**
1. Find plugin directory (for macOS it's ~/Library/Application Support/IntelliJIdea*/idea-gitignore/lib).
2. Change version in file idea-gitignore-1.7.6.jar/unzip://META-INF/plugin.xml to something not blacklisted like 1.7.7.
3. Re-start IntelliJ IDEA.
4. Watch for this thread carefully and undo steps 1-3 if next release version will be the same as you specified manually.

**Comment by robert-cody** [comment] 2017-08-21 06:43
@hsz count me too please, ready to check-out RC on custom plugin channel or just as file from disk.

**Comment by filiphr** [comment] 2017-08-21 06:59
@hsz I can also try it out. However, I think that it would be good if someone from Jetbrains steps in and checks the changes and even tries out the RC. 

I have to stress out that the `.ignore` plugin is the most downloaded non Jetbrains plugin out there (2nd after Scala). I really appreciate the guys from Jetbrains and analyzing the issues and opening issues to resolve them. This is why I think that it would be great if they can check it out too.

**Comment by hsz** [comment] 2017-08-21 09:17
@justinlynn Thanks for this suggestion!

I have created `eap` release channel that will contain all release candidates that will appear in the feature.
Right now I have published `v2.1.0-RC.1` version.

EAP channel URL: https://plugins.jetbrains.com/plugins/eap/7495

Instruction about adding this channel to your IDE you can find also in readme in [EAP section](https://github.com/hsz/idea-gitignore#early-access-preview-repository-channel)

I will be very grateful for joining EAP channel and some tests of the latest RC.


As @filiphr has suggested - is it possible for you @nicity to verify if this version resolves all of the issues that you have noticed?

**Comment by Pluto1010** [comment] 2017-08-21 09:25
@hsz Thank you!
I've installed 2.1.0-RC.1 and will test it over the next days.

**Comment by alexilyaev** [comment] 2017-08-21 11:41
Getting the error in latest stable version:
```
Plugin Error
Problems found loading plugins:
The following plugins are incompatible with the current IDE build: .ignore
```

WebStorm 2017.2.2
Build #WS-172.3757.55, built on August 15, 2017
Licensed to Alex Ilyaev
Subscription is active until July 12, 2018
JRE: 1.8.0_152-release-915-b10 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by robert-cody** [comment] 2017-08-21 11:54
Just installed 2.1.0-RC.1 and got this warning:
<img width="372" alt="1" src="https://user-images.githubusercontent.com/13272122/29517801-6dfc0696-867f-11e7-863d-79e32a5030ae.png">
While these tracked ignored files was only 1 item - my project root and it's not listed in .gitignore.

**Comment by dejan2609** [comment] 2017-08-21 12:03
Version **_2.1.0-RC.1_** works on Windows; I'll post an update in case of issues.
```
IntelliJ IDEA (Community Edition) 2017.2.3 EAP
Build #IC-172.3968.1, built on August 15, 2017
JRE: 1.8.0_131-b11 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
```

**Comment by hsz** [comment] 2017-08-21 12:05
@robert-cody This warning about tracked files is already reported and will be fixed with #400

**Comment by BorzdeG** [comment] 2017-08-21 12:07
works on Mac OS:

IntelliJ IDEA 2017.2.3 EAP
Build #IU-172.3968.1, built on August 15, 2017
JRE: 1.8.0_152-release-915-b10 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by Caravus** [comment] 2017-08-21 12:54
EAP works for me

**Comment by BorzdeG** [comment] 2017-08-21 12:55
#448

**Comment by fengcen** [comment] 2017-08-21 14:28
"hide ignored files" not work

**Comment by Scott-G** [comment] 2017-08-21 15:45
Seems fine here. Thanks for your efforts.

PhpStorm 2017.2.2 EAP
Build #PS-172.3757.60, built on August 16, 2017
JRE: 1.8.0_152-release-915-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by justinlynn** [comment] 2017-08-22 01:26
hmm, on 2017.2.3 EAP (latest) the RC.1 version does not properly re-hide files at the top-level in the Project explorer when show/hide ignored files is toggled from the right-click context menu (no exception is thrown). Additionally, new version does not pick up global ignore file set with `core.excludesfile` git configuration setting. Otherwise it appears to work quite well.

**Comment by xrhou** [comment] 2017-08-22 02:18
2017/8/22 
2017.2.2 stable release
mac osSierra 10.12.6
oracle java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
上午8:28	Plugin Error
Problems found loading plugins:
The following plugins are incompatible with the current IDE build: .ignore

**Comment by hsz** [comment] 2017-08-22 08:29
@fengcen @justinlynn Thanks.

Can you please check if those bugs were fixed for you with `v2.1.0-RC.2` ?

**Comment by fengcen** [comment] 2017-08-22 08:59
Sometimes not work. Steps to reproduce:
Install Rust plugin, restart, or uninstall Rust plugin, restart.
I try it on windows.

**Closed** 2017-08-22 20:16 UTC
Labels: bug, ready for release

**Comment by hsz** [comment] 2017-08-22 20:18
New version **v2.1.0** has been released just right now.

**Comment by justinlynn** [comment] 2017-08-23 06:55
@hsz apologies. I've installed the v2.1.0 plugin. Most of the issues have been addressed; however, on 2017.2.3 RC3, I now note that it appears that the entries that the plugin has trouble with are all globbed entries (for example "*.pdf"). Once the glob is removed things work as expected. Once I can get a minimal test case I'll file a new issue. Much faster! Great work!

**Comment by hsz** [comment] 2017-08-23 06:58
@justinlynn Thanks!

Did you notice any of #450 or #414 ? They're not reproducible for me, unfortunately.

**Comment by justinlynn** [comment] 2017-08-23 06:59
@hsz negative, no exceptions thrown by the plugin as of yet on 2017.2.3 RC3 on Linux.

**Comment by york-xtrem** [comment] 2017-08-23 07:08
I am installing from the zip in mac osx (intellij IDEA 2017.2.2) and I get this error:

> Fail to load plugin descriptor from file idea-gitignore-2.1.0.zip

Since the plugin searcher does not appear yet

**Comment by F21** [comment] 2017-08-23 07:09
@york-xtrem I was able to install it using the plugin manager by following these directions: https://github.com/hsz/idea-gitignore#early-access-preview-repository-channel

**Comment by hsz** [comment] 2017-08-23 07:10
@york-xterm I had to remove this version from JB repo because of above errors. I'm on it right now.

**Comment by york-xtrem** [comment] 2017-08-23 07:22
@F21 and @hsz apologize for ignorance! It is already installed, I have tried it in several projects and it works to me as expected;)

**Comment by bamapookie** [comment] 2017-08-24 16:44
Using 2.1.1 on 

IntelliJ IDEA 2017.2.3
Build #IU-172.3968.16, built on August 21, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

Confirm no issues.
