### ISSUE TITLE
Incorrect "You are editing file which is ignored" for non vcs ignore files

### ISSUE THREAD

**Issue by mcfedr** [hsz/idea-gitignore#356] opened 2017-04-25 11:23 UTC
My project has both `.gitignore` and `.dockerignore` files.

The `.dockerignore` file lists quite a lot of files that are just not needed for docker, but are still part of the project, tracked in git, etc.

It seems that only the `gitignore` (or related svn/etc) files should trigger the "You are editing file which is ignored" flag, everything else, eg `dockerignore`, `npmignore` shouldn't cause this.

**Comment by clintonb** [comment] 2017-04-27 14:24
I have disabled the plugin due to this issue.

**Comment by WileESpaghetti** [comment] 2017-04-28 17:40
#352 is a similar issue

**Comment by hsz** [comment] 2017-05-31 22:19
@mcfedr @clintonb @WileESpaghetti Thanks for this report.

Files in the Project View are grayed only if you have ignoring enabled for the specific type. Can you please verify if you have _Enable ignoring_ checkbox unchecked for _Docker_ ?

![image](https://cloud.githubusercontent.com/assets/108333/26656343/eeb4a718-465e-11e7-90c4-06be0705fff8.png)

**Comment by hsz** [comment] 2017-05-31 22:24
CC @bobbylight @tflori @edro @MrNeilRobbins @jturkel @robertspari @yingbo @crrobinson14 @mko-x

**Comment by tflori** [comment] 2017-06-01 04:50
@hsz I just checked it once more. npm ignoring is disabled. files are greyed out anyway.
![bildschirmfoto von 2017-06-01 06-36-54](https://cloud.githubusercontent.com/assets/4855611/26664957/3ea989f0-4696-11e7-809b-4c889800f558.png)
![bildschirmfoto von 2017-06-01 06-49-39](https://cloud.githubusercontent.com/assets/4855611/26664986/90c68fd0-4696-11e7-90d5-63c0d9f28106.png)

**Comment by hsz** [comment] 2017-06-01 05:26
@tflori Ouch, that's strange.

I'll try to reproduce this scenario with your `angular-translator` repository today. Thanks for the feedback!

**Comment by jhwegener** [comment] 2017-06-01 10:19
Same as @tflori said for me here. But: files are not grayed out, if I uncheck the 'Show in "New > .ignore file" option also.

**Comment by hsz** [comment] 2017-06-01 10:58
@tflori @jhwegener Can you guys please verify it this issue is resolved with following build?

Keep in mind that it is still WIP version so something else may be broken. ;-)

[idea-gitignore-2.0-0106217.zip](https://github.com/hsz/idea-gitignore/files/1044501/idea-gitignore-2.0-0106217.zip)

**Comment by tflori** [comment] 2017-06-02 04:26
Yes, thanks! This is working as expected

**Comment by hsz** [comment] 2017-06-02 04:48
@tflori thank you for the confirmation. We're closer to the release. 😉

**Comment by jhwegener** [comment] 2017-06-02 07:10
@hsz that works quite fine! THX!

**Closed** 2017-07-29 23:13 UTC
Labels: bug, ready for release
