### ISSUE TITLE
Change color of ignored files in project view

### ISSUE THREAD

**Issue by gerritwalther** [hsz/idea-gitignore#87] opened 2015-03-03 18:28 UTC
Is there any way to change the color of the ignored files? Grey is also used for deleted files and can be confusing. I think for svn it is something in the direction of #CCFF00.

**Comment by Azaret** [comment] 2015-03-03 18:33
Also, could we have the option to not color the files and folders ?
I some projects with nested repositories, and now all the nested ones are grey.

**Comment by hsz** [comment] 2015-03-03 19:25
@gerritwalther 

Go to <kbd>Settings</kbd> > <kbd>Ignore files support</kbd> and click an anchor <kbd>Edit ignored files text color & font</kbd> 

@Azaret 

You can disable the color in this place too, however with next release I'll allow to disable this feature from the settings. Stay tuned.

**Comment by hsz** [comment] 2015-03-03 20:55
@Azaret Already implemented and will be pushed to the JetBrains repository soon.

![image](https://cloud.githubusercontent.com/assets/108333/6472065/feeb25da-c1ef-11e4-98d1-22652110c445.png)

**Comment by gerritwalther** [comment] 2015-03-03 22:20
I already clicked the anchor leading me to searching for ".ignore" in the settings. But then I only find options to change the colors for the editor view. Not for changing the colors of ignored files in the project view. Am I blind?

**Comment by hsz** [comment] 2015-03-03 22:26
It should point to the:

<kbd>Editor</kbd> > <kbd>Colors & Fonts</kbd> > <kbd>File Status</kbd> > <kbd>Ignored (.ignore plugin)</kbd>

![image](https://cloud.githubusercontent.com/assets/108333/6473884/b6d3d168-c1fc-11e4-8ae4-3c74b930302f.png)

**Comment by hsz** [comment] 2015-03-03 23:00
Feature to disable coloring introduced with release `v1.0.1`.

Please confirm if everything is fine.

**Comment by Azaret** [comment] 2015-03-04 08:20
@hsz 
Thanks for the quick update, here get some coins :)

For the ```Edit ignored files text color & font``` It doesn't point to the right place either at first, and it's a bit confusing at first.

![image](https://cloud.githubusercontent.com/assets/1201743/6480075/a097a8cc-c24f-11e4-99bf-a75326bcebfa.png)

**Comment by hsz** [comment] 2015-03-04 09:32
@Azaret Ok, it looks like issue with new settings structure in IntelliJ 14.

**Comment by Knallcharge** [comment] 2015-03-04 10:26
"color ignored files" stopped working for me after todays update (to 1.0.2), it did yesterday (loved it!)
the checkbox for "Enable ignored file status coloring" is checked and I set the foreground-color in the File Status-config (like shown above), but to no avail

**Comment by gerritwalther** [comment] 2015-03-04 12:04
Don't know if the <kbd>File Status</kbd> point was there yesterday, but I found it now. Unfortunately I don't get there when clicking on the `Edit ignored files text color & font` anchor. Below is a screenshot of where I get when clicking on it. I'm using Intellij Idea 14.0.3 (Ultimate Edition).

![selection_008](https://cloud.githubusercontent.com/assets/1128084/6483173/3fb590ae-c26e-11e4-94a2-0d941a104450.png)

**Comment by ohcibi** [comment] 2015-03-04 20:25
I'm also experiencing what @gerritwalther posted. Additionally after the update, the coloring of the files isn't working at all anymore.

**Comment by hsz** [comment] 2015-03-04 21:18
@ohcibi fix for files coloring is already committed and will be in the next release. 

However there is a problem with the linking in the settings but I'll find out some solution for this.

**Comment by danieljimenez** [comment] 2015-03-06 22:06
I'm seeing same as what @gerritwalther posted.

**Comment by michaelperrygoodman** [comment] 2015-03-11 20:26
Another confirmation for broken file coloring (particularly the ignored files, new and updated file seem to be working alright). Any word on next release date? Thanks for your great plugin.

**Comment by gcortes** [comment] 2015-03-19 17:27
I'm not seeing the file color either. I have the same color scheme as hsz above except my default foreground color is a yellow-orange. This is in PHPStorm 8.0.3. I tried right clicking on a file, choosing Ignore File and adding it specifically. It was already there as part of a global ignore. Could it be PHPStorm is having a problem knowing which files are ignored? I have no color problems with non-ignored files. They worked fine before and after I installed your plugin.

**Comment by hsz** [comment] 2015-04-13 07:42
Ok, there was a problem with coloring in the previous version. With release `v1.1` it works.

I've also wanted to create a short link to the color settings but IntelliJ API doesn't allow to select proper value in v13. In v14 it's not possible at all right now - so I've removed it.

Anyway you can still go to the Ignore color settings by your own with this path:

<kbd>Settings</kbd> > <kbd>Editor</kbd> > <kbd>Colors & Fonts</kbd> > <kbd>File Status> > <kbd>Ignored (.ignore plugin)</kbd>

![image](https://cloud.githubusercontent.com/assets/108333/7111493/bdd0d3a6-e1c0-11e4-8abf-850e4ad1d7c6.png)



Please verify if coloring and changing the ignore color works well.

Also with new version it's possible to exclude some file types from coloring (i.e. you can color only `.gitignore` and exclude `.jshintignore`):

![image](https://cloud.githubusercontent.com/assets/108333/7111554/6800c7a0-e1c1-11e4-9f5e-0b21a11cdbd0.png)

**Comment by gerritwalther** [comment] 2015-04-13 07:59
Colors work again for me. It would be great if you could change the background color for ignored files as well, but it seems to me thats not possible with intellij.

**Comment by gallalsf** [comment] 2015-04-13 10:32
I can confirm that colors are working again, thanks

**Closed** 2015-04-13 10:57 UTC

**Comment by hsz** [comment] 2015-04-13 12:57
@gerritwalther 
It's not possible to change anything else than text color because of IntelliJ API, sorry.

**Comment by gerritwalther** [comment] 2015-04-13 18:07
@hsz
Yeah, I thought so when looking at other color options.

Anyway, thanks for all your work and help.

**Comment by phestermcs** [comment] 2015-10-01 15:33
Understanding Intellij 15 is still EAP, but it appears ignored files are no longer being colored correctly in Intellij IDEA 142.5047 :(

**Comment by MightyPork** [comment] 2016-02-01 19:32
I just had this issue (files not colored).
It got fixed after deleting `~/.WebIde100/system/vcs-users`.

Just putting it here in case it helps someone in the future.

**Comment by gertmedia24** [comment] 2017-11-08 13:51
hi, I am finding this is not working:

Settings > Editor > Colors & Fonts > File Status > Ignored (.ignore plugin)

Change colour to something (yellow lets say) ... changes not being applied ... files that are gitignored are appearing same colour as before

PhpStorm Info:

> PhpStorm 2017.2.1
> Build #PS-172.3544.41, built on August 2, 2017
> Subscription is active until May 17, 2018
> JRE: 1.8.0_152-release-915-b6 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Mac OS X 10.12.6
