### ISSUE TITLE
Throwable: Accessing 'IgnoreFilesIndex' during processing 'FilenameIndex'.

### ISSUE THREAD

**Issue by cviebrock** [hsz/idea-gitignore#456] opened 2017-08-25 14:19 UTC
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

PHPStorm starts up with the following error:

```
Throwable: Accessing 'IgnoreFilesIndex' during processing 'FilenameIndex'.
Nested different indices processing may cause deadlock
```

No stack trace is available, AFAICT.

### Steps to Reproduce

1. Enable the plugin
2. Restart PHPStorm

**Expected behavior:** No error message.

**Actual behavior:** Error message is displayed.

**Reproduces how often:** All the time, if the plugin in enabled (error stops if plugin is disabled).

### Versions

**Plugin:** 2.1.1

**IDE:**

```
PhpStorm 2016.2.2
Build #PS-162.2380.11, built on October 24, 2016
JRE: 1.8.0_112-release-287-b3 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**OS:** 

```
Mac OS X 10.12.6
```

**Comment by hsz** [comment] 2017-08-27 12:11
@cviebrock 

This issue is caused by IntelliJ itself.

This issue is reported here: https://youtrack.jetbrains.com/issue/IDEA-159135
It was fixed with IntelliJ 2016.2.3

Please update your IDE.

**Closed by hsz** 2017-08-27 12:11 UTC
