### ISSUE TITLE
Incompatible with Gogland EAP 11

### ISSUE THREAD

**Issue by michael1011** [hsz/idea-gitignore#405] opened 2017-08-01 19:51 UTC
The plugin can not be found in the repository of the IDE and if you install it with a zip file and restart Gogland this error is shown:

```
9:44 PM Plugin Error
Problems found loading plugins:
The following plugins are incompatible with the current IDE build: .ignore
```

**Comment by damagedcode** [comment] 2017-08-02 06:49
same error

**Comment by hsz** [comment] 2017-08-10 19:03
Duplicate of #408

**Closed by hsz** 2017-08-10 19:03 UTC
Labels: bug
