### ISSUE TITLE
The following plugins are incompatible with the current IDE build: .ignore

### ISSUE THREAD

**Issue by simvolice** [hsz/idea-gitignore#431] opened 2017-08-17 08:10 UTC
WebStorm 2017.2.2
Build #WS-172.3757.55, built on August 15, 2017

JRE: 1.8.0_152-release-915-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by hsz** [comment] 2017-08-17 08:11
Duplicate of #408

**Closed by hsz** 2017-08-17 08:11 UTC
