### ISSUE TITLE
What's new showing up every time project opened.

### ISSUE THREAD

**Issue by kumold** [hsz/idea-gitignore#321] opened 2017-02-15 11:49 UTC
"What's new" showing up every time project opened.

![2017-02-15_17-48-34](https://cloud.githubusercontent.com/assets/489406/22973139/02163eb2-f3a7-11e6-9ee8-920e1032488b.png)

**Comment by hsz** [comment] 2017-02-15 11:54
@kumold Duplicate of #311

**Closed by hsz** 2017-02-15 11:54 UTC
