### ISSUE TITLE
gitignore scan .gitignore file in ver 1.3 

### ISSUE THREAD

**Issue by lovehcf-duplicate** [hsz/idea-gitignore#204] opened 2016-03-21 06:45 UTC
Hi, everytime I open my idea integrated .ignore both to scan all moudles' .gitignore file,lead to my ide too broken and unable to work;At the same time waiting for a long time to unfold the moudle's src etc.
![image](https://cloud.githubusercontent.com/assets/731312/13912011/2379b41e-ef73-11e5-9a0e-cac14790c518.png)
![image](https://cloud.githubusercontent.com/assets/731312/13912023/5d890682-ef73-11e5-8bd2-b1eeb34e32e9.png)

Thanks.

**Comment by alxbauer** [comment] 2016-03-21 07:07
Same here.

**Comment by hsz** [comment] 2016-03-21 07:08
@lovehcf-duplicate @alxbauer Thanks for the quick report. Can you provide me more information about the Project configuration - i.e. submodules, gitignore content, etc - I'll fix it asap.

**Comment by awerment** [comment] 2016-03-21 08:50
Also having this issue with a larger codebase. Notable: when opening module directories for the first time after (re)starting the IDE - it takes a couple seconds and my network traffic spikes.

**Comment by hsz** [comment] 2016-03-21 08:52
@awerment I do not use any network in my plugin, so it's a different reason of this peak.
Can you provide me some information about your IDE, environment, project structure ?
Is it public one so I would like to fetch it too ?

**Comment by awerment** [comment] 2016-03-21 09:29
Thanks for the super quick reply. Unfortunately this is a closed internal project. 

I'm running IntelliJ Ultimate 2016.1, 64bit on Win8.

The project layout is quite chaotic, basically it's one parent module which contains sub-directories - one of which is a nested maven module structure. The other directories contain former eclipse projects (we're migrating, don't ask...), they are not managed as modules in IntelliJ. 

After going through some of the old projects, I noticed they themselves contained .gitignore files. After removing them (only one remains for the parent directory), the IDE is usable. But the root issue still seems to remain - opening any module folders for the first time takes longer than it does without the plugin enabled. The network spikes also remain, not sure what's the cause there.

**Comment by lovehcf-duplicate** [comment] 2016-03-21 10:10
One of gitignores' content:

#Android generated
bin
gen

#Eclipse
.project
.classpath
.settings
#IntelliJ IDEA
.idea
*.iml
classes
out
production

#Maven
target
release.properties
pom.xml.*

#Command line
local.properties
proguard-project.txt

# Android Studio
.gradle
local.properties
.idea/workspace.xml
.idea/libraries
.DS_Store
build

# Log
*.log

**Comment by lovehcf-duplicate** [comment] 2016-03-21 10:13
One of gitignores' content is as follows:

![image](https://cloud.githubusercontent.com/assets/731312/13915568/8648bbea-ef90-11e5-997e-106ea0bb2f02.png)

**Comment by languanghao** [comment] 2016-03-21 14:05
I also have same problem after upgrade to v1.3. It cause open floder slow and also make right click menu show slow

**Comment by bmcclure** [comment] 2016-03-21 21:21
Same problem here, I think.

Opening pretty much any full Drupal website in PhpStorm is causing the task "Indexing ignore files" to take several minutes, during which time my IDE is almost completely unresponsive.

After the process completes, then the IDE remains very slow and unresponsive for at least 30 seconds more. Finally, after that it seems to work more quickly.

This was not an issue at all until the update I just installed to 1.3 today.

**Comment by pswai** [comment] 2016-03-22 03:50
I am experiencing the performance impact too after upgrading to 1.3. WebStorm becomes very slow to be usable. Disabling the plugin regains the performance.

**Comment by z5864703** [comment] 2016-03-22 03:53
After updating to 1.3 I also emergence of this issue, the project configuration without any changes. Every time you open phpstorm scans items in all .gitignore, then scanned the entire phpstorm reaction becomes very slow, and then pull the situation becomes more serious

**Comment by Ornitier** [comment] 2016-03-22 19:05
Same as @bmcclure here.
Can't work on Drupal projects, had to disable .ignore plugin to continue :(

**Comment by hsz** [comment] 2016-03-22 19:15
@lovehcf-duplicate @alxbauer @awerment @languanghao @bmcclure @pswai @z5864703 @Ornitier 

Can you guys please check if following version fixes this issue ?

[idea-gitignore.zip](https://github.com/hsz/idea-gitignore/files/184790/idea-gitignore.zip)

**Comment by z5864703** [comment] 2016-03-23 01:32
@hsz 
Unable to install the plugin.
Install plugin from disk ... After the restart phpstorm
After the restart widget disappear

**Comment by lovehcf-duplicate** [comment] 2016-03-23 02:39
@hsz I'm so sorry,unable to install the plugin.Install the plugin from disk and then restart IDE(Android Studio),the widget disappear.

**Comment by pswai** [comment] 2016-03-23 03:16
@hsz I am having the same issue. The plugin disappear from the list after restarting WebStorm

**Comment by Viky-zhang** [comment] 2016-03-23 03:34
the same problem as @lovehcf-duplicate 
IDE: PhpStorm
.ignore version: 1.3
my project: latest [Laravel](https://laravel.com/docs/5.2)

**Comment by hsz** [comment] 2016-03-23 07:05
@z5864703 @lovehcf-duplicate @pswai @VanDalkvist 

Have you **unzip** this file before and install **idea-gitignore.jar** file ?

**Comment by pswai** [comment] 2016-03-23 11:46
@hsz Installing the jar works! But it gives this error after restarting

`7:45:11 PM NullPointerException: mobi.hsz.idea.gitignore.UpdateComponent@4bdffe16`

**Comment by hsz** [comment] 2016-03-23 11:49
@pswai Ok, please ignore this error for the moment - what about the performance ?

**Comment by lovehcf-duplicate** [comment] 2016-03-23 12:38
@hsz Thank you for reminding,the jar works.

**Comment by pswai** [comment] 2016-03-23 12:43
@hsz Much better. Now it won't make WebStorm completely unusable but the lagginess is still there. I have tried to enable/disable it several times and I can feel the difference. It is especially noticeable when using Go To File function, the autocomplete is lagging with small freeze sometimes.

**Comment by primeinc** [comment] 2016-03-23 19:29
Having the same issue, even with the attached jar, PhpStorm 2016.1 on Win 8.1 with Laravel Project. After it's done with the indexing there is a significant lag with just typing/code completion and just about everything else. Phpstorm idle (after indexing) cpu usage is ~6% with the plugin enabled and 0% with it disabled.

Tried to downgrade to 1.2, but get an error
```
Cannot get state after load
java.lang.NullPointerException
	at mobi.hsz.idea.gitignore.settings.IgnoreSettings.getState(IgnoreSettings.java:145)
	at mobi.hsz.idea.gitignore.settings.IgnoreSettings.getState(IgnoreSettings.java:50)
	at com.intellij.configurationStore.StateGetter.close(StorageBaseEx.kt:57)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:294)
...
```

**Comment by eman1986** [comment] 2016-03-31 02:58
I also am experiencing this. Just updated and PhpStorm just crawls, disabling this plugin and its back to being lightning fast.

Really hope this can get resolved, I do enjoy this plugin.

**Comment by Suseika** [comment] 2016-03-31 03:36
I now experience this slowdown with version 1.3.1 of the plugin. The symptoms are the same as in the opening post: loading icon for every .gitignore in the project and massive CPU load. I didn't get this problem before. Not sure what version I had installed, I think it was 1.3.0 that was working fine for me. Disabling the plugin fixed the issue.

**Comment by Musiksammler** [comment] 2016-03-31 07:16
I've updated the plugin to version 1.3.1 this morning (linux ubuntu machine) and phpstorm went painfully slow. After disabling the plugin everything worked as before.

**Comment by hsz** [comment] 2016-03-31 07:18
Can you guys provide me more information about it ? What is the project structure, how mony ignore files do you have (in subfolders too) ? What is the content of the main `.gitignore` file ?

Do you have any public project, so I could fetch it ?

I'll try to get as much information as I can and deliver the fix today.

**Comment by primeinc** [comment] 2016-03-31 07:22
https://github.com/primeinc/csg-sam is the project I've been working on that has the problems described.

**Comment by Musiksammler** [comment] 2016-03-31 07:23
In my case it's a company internal project. Sorry, no public respositories.

A "find . -type f -name ".gitignore" | wc -l" points out a number of 68.

The main .gitgnore looks like this:

```
.idea/
.mage
__dev
phpinfo.php
composer.lock
/public/images/artikel/
/public/images/cms/brand-**/*.jpg
/public/images/cms/brand-**/*.jpeg
/public/images/cms/brand-**/*.png
/public/images/cms/brand-**/*.gif
/images/cms/brand-**/*.jpg
/images/cms/brand-**/*.jpeg
/images/cms/brand-**/*.png
/images/cms/brand-**/*.gif

# Smarty / Prototype #
######################
/prototype/cache/
/prototype/fonts/
/prototype/stylesheets/
/prototype/images/
/prototype/templates_c/
/prototype/bower_components/
/prototype/node_modules/
/prototype/js/libs
/prototype/js/main.js

/vendor/**/.git
*.min.min.*
bundle.min.js
```

**Comment by Suseika** [comment] 2016-03-31 13:28
https://github.com/Suseika/tendiwa

Here is the repository I'm having problems with in 1.3.1. It has a lot of submodules with their own gitignore files. Also, if it may be relevant, in its `.gitmodules` file, each of 30 submodules has `ignore = all` option.

**Comment by vRallev** [comment] 2016-03-31 15:02
Here is thread dump from Android Studio, if this is helpful: https://code.google.com/p/android/issues/detail?id=205521 Tor Norbye added also a short explanation.

**Comment by azeos** [comment] 2016-03-31 18:17
After doing a "File -> Invalidate Caches / Restart" and let the indexing finish, it's working fine.
PhpStorm 2016.1
.ignore 1.3.1

**Comment by Suseika** [comment] 2016-03-31 18:22
@azeos Does the whole gitignore thing run again if you restart your IDE?

**Comment by azeos** [comment] 2016-03-31 18:32
@Suseika I hadn't tried, but unfortunately yes, the problem reappears

**Comment by Viky-zhang** [comment] 2016-04-01 01:10
@azeos , should I Invalidate Caches for all project? because I have more than 10 projects.

**Comment by azeos** [comment] 2016-04-01 16:53
@Viky-zhang The problem reappears after you close and open again the application. So, disabling the plugin is the only -apparent- solution. Try that first and may be you don't need to invalidate the caches.

**Comment by hsz** [comment] 2016-04-02 00:58
Thank you everyone for the support. I've prepared a fixed version, but before pushing it to the JetBrains repository, I'd like to ask you if you can verify it and confirm that none of above issues appears again.

Please remember to unzip the package and install **jar** file.

[idea-gitignore-1.3.1-2040257.zip](https://github.com/hsz/idea-gitignore/files/200607/idea-gitignore-1.3.1-2040257.zip)

**Comment by Suseika** [comment] 2016-04-02 01:12
@hsz IDEA says that the plugin I'm trying to load from disk is not compatible with my installation. I've got IDEA IC-145.257

**Comment by azeos** [comment] 2016-04-03 01:50
@hsz Settings -> Plugins -> Install plugin from disk -> idea-gitignore-1.3.1-2040257.jar and I get "Plugin '.ignore' is incompatible with this installation". PhpStorm 2016.1 x64 @ Win7 x64.

**Comment by Suseika** [comment] 2016-04-03 02:43
@azeos Same here. IDEA IC-145.257

**Comment by hsz** [comment] 2016-04-03 08:08
Ok, sorry about that - gradle plugin by default limits the IDE versions.

Please install following package (**without unzipping** - select zip file - this one is 'jar-less' package).

Thanks !
[idea-gitignore-1.3.1-3040947.zip](https://github.com/hsz/idea-gitignore/files/201232/idea-gitignore-1.3.1-3040947.zip)

**Comment by Suseika** [comment] 2016-04-03 15:16
@hsz I installed the plugin and restarted the IDE. After it reloaded, I had a massive responsiveness degradation in the IDE with high CPU usage, but without the series of messages notifying that .gitignore files are being processed. After some time the slowdown ended. Then I restarted the IDE, and the same temporary slowdown appears for several minutes after starting.

So the only thing that has changed is that now it doesn't show me the notifications attached in the opening post.

**Comment by hsz** [comment] 2016-04-03 15:23
@Suseika I have checked my plugin with profiler tool and it takes just a few % of CPU at the startup so I bet it's not a really caused by the .ignore plugin.

Can you post a CPU snapshot ?

**Comment by Suseika** [comment] 2016-04-03 15:43
@hsz Sorry, I can't:

> IntelliJ IDEA and PyCharm Community Editions do not include a YourKit profiler agent, because the YourKit agent library is not open-source.

**Comment by Suseika** [comment] 2016-04-03 15:46
@hsz Can you clone the repository I posted above and try to load it in IDEA with the plugin enabled to see if you get any slowdown at startup? The repository has all the necessary project files for IDEA.

**Comment by primeinc** [comment] 2016-04-03 21:28
https://drive.google.com/file/d/0B-3lG2AWxus5SFV3TDVjTWdvUFE/view?usp=sharing

I've attached two snapshots, first one is without the plugin enabled.

Maybe a misconfig is calling `git config --global core.excludesfile` with no parameters thousands of times.

I don't have a global exclude file setup.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/4395149/14235040/e70ce386-f9c0-11e5-9c73-9dde036a0877.png)

**Comment by primeinc** [comment] 2016-04-03 22:13
Confirmed Windows workaround:
```
copy NUL "%USERPROFILE%\.gitignore"
git config --global core.excludesfile "%USERPROFILE%\.gitignore"
```
Probable? *nix workaround:
```
touch ~/.gitignore
git config --global core.excludesfile '~/.gitignore'
```

All performance issues go away, at least with `idea-gitignore-1.3.1-3040947`

**Comment by hsz** [comment] 2016-04-04 08:02
@primeinc That was a bull's-eye. I've prepared a fix. Can you confirm that it fixes the issue?

[idea-gitignore-1.3.1-4041002.zip](https://github.com/hsz/idea-gitignore/files/201954/idea-gitignore-1.3.1-4041002.zip)

**Comment by 76200** [comment] 2016-04-04 08:35
@hsz this fix seems fine

**Comment by primeinc** [comment] 2016-04-04 20:15
yep I ran `git config --global --unset core.excludesfile` and restarted phpstorm with the plugin active. Works great still. Also tested it with `*` in my global exclude and it worked as expected. Glad we could track this down.

**Comment by hsz** [comment] 2016-04-05 07:18
@primeinc That's a good news! Thank you again for the help in this case.

What about the others? Do you also can confirm the performance improvement?

**Comment by Musiksammler** [comment] 2016-04-05 11:44
*thumbs-up*

Look good!

**Closed** 2016-04-05 18:23 UTC
Labels: bug

**Comment by Viky-zhang** [comment] 2016-04-06 01:00
In PhpStorm 2016.1. Look good !
 @hsz

**Comment by azeos** [comment] 2016-04-06 03:34
@hsz Thanks for the fix!
