### ISSUE TITLE
folder/ syntax does not grey folders in sub-folders

### ISSUE THREAD

**Issue by davidshen84** [hsz/idea-gitignore#189] opened 2016-02-02 04:48 UTC
Folder structure:

 - app
  - ignore
  - some_data
    - ignore

Adding `ignore/` in `.gitignore` file will cause *git* to ignore both *ignore* folder, but this plugin cannot set the 2nd *ignore* folder to grey. I think this is inconsistent with *git* behavior.

**Comment by davidshen84** [comment] 2016-02-02 04:50
BTW, I found this issue while using *Android Studio 2.0 Preview 9*. I also tried to restart the studio.

**Comment by hsz** [comment] 2016-03-17 17:23
@davidshen84 Thank you for reporting it, however I cannot reproduce it.

For example with following files tree:

    .
    ├── dir
    │   ├── a.txt
    │   └── b.txt
    ├── foo
    │   ├── 1.txt
    │   └── dir
    │       ├── 2.txt
    │       └── 3.txt
    └── foo.txt

I get the result:

![image](https://cloud.githubusercontent.com/assets/108333/13854747/3ed55500-ec6d-11e5-82f2-ceda40003083.png)

Also git reports them as ignored:

    $  git ls-files --others --ignored --exclude-standard
    abs/dir/2.txt
    abs/dir/3.txt
    dir/a.txt
    dir/b.txt

**Comment by davidshen84** [comment] 2016-03-18 11:20
Indeed, I cannot reproduce it either. I guess it is fixed in some recent
update.

On Fri, Mar 18, 2016 at 1:23 AM Jakub Chrzanowski <notifications@github.com>
wrote:

> @davidshen84 <https://github.com/davidshen84> Thank you for reporting it,
> however I cannot reproduce it.
>
> For example with following files tree:
>
> .
> ├── dir
> │   ├── a.txt
> │   └── b.txt
> ├── foo
> │   ├── 1.txt
> │   └── dir
> │       ├── 2.txt
> │       └── 3.txt
> └── foo.txt
>
> I get the result:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/108333/13854747/3ed55500-ec6d-11e5-82f2-ceda40003083.png>
>
> Also git reports them as ignored:
>
> $  git ls-files --others --ignored --exclude-standard
> abs/dir/2.txt
> abs/dir/3.txt
> dir/a.txt
> dir/b.txt
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hsz/idea-gitignore/issues/189#issuecomment-197985412>
>
-- 

Regards,
David

**Comment by hsz** [comment] 2016-03-18 11:21
Ok, thank you for the confirmation, closing.

**Closed by hsz** 2016-03-18 11:21 UTC
Labels: cannot reproduce
