### ISSUE TITLE
Not supported on WebStorm 2017.2.2

### ISSUE THREAD

**Issue by FedeMarshall** [hsz/idea-gitignore#429] opened 2017-08-16 15:06 UTC
Hello!
I've just updated WebStorm to its latest version and when I've restarted it I got this message saying that .ignore plugin is not compatible.

This is my set up:

> 
Build
 #WS-172.3757.55, built on August 15, 2017
JRE: 1.8.0_152-release-915-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Node version: 8.4.0
> 

Thanks!

**Comment by hsz** [comment] 2017-08-16 15:18
@FedeMarshall duplicate of #408

**Closed by hsz** 2017-08-16 15:18 UTC
Labels: bug, duplicate
