### ISSUE TITLE
Already disposed: Project (Disposed)

### ISSUE THREAD

**Issue by BorzdeG** [hsz/idea-gitignore#110] opened 2015-04-16 16:39 UTC
The error occurs at the moment when I opened another project in the same window. In the error specified project (MY_PROJECT) that closed IDEA

IDEA: IU-141.588

```
Already disposed: Project (Disposed) MY_PROJECT
java.lang.AssertionError: Already disposed: Project (Disposed) foxtrot-hybris
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:282)
	at com.intellij.openapi.project.impl.ProjectImpl.getStateStore(ProjectImpl.java:187)
	at com.intellij.openapi.project.impl.ProjectImpl.getBaseDir(ProjectImpl.java:238)
	at mobi.hsz.idea.gitignore.lang.kind.FossilLanguage.getOuterFile(FossilLanguage.java:74)
	at mobi.hsz.idea.gitignore.IgnoreManager$4.run(IgnoreManager.java:298)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by hsz** [comment] 2015-04-16 17:45
Duplicate of #109

**Closed by hsz** 2015-04-16 17:45 UTC
Labels: duplicate
